<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\HospitalStaff;

class HospitalStaffSeeder extends Seeder
{
    public function run(): void
    {
        $staffMembers = [
            [
                'first_name' => 'Ezra',
                'last_name' => 'Valdez',
                'date_of_birth' => '1978-03-22',
                'gender' => 'Male',
                'national_id' => 'HX28374691',
                'contact_email' => 'ezravaldez@gmail.com',
                'phone_number' => '09171230001',
                'address' => '57 Aurora Lane, Lipa City',
                'job_title' => 'Pulmonologist',
                'department' => 'Respiratory Care',
                'hire_date' => '2014-09-12',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'MD, Fellow in Pulmonology',
                'work_experience' => '12 years specializing in respiratory infections and critical care.',
                'allocation' => 'ICU Ward',
            ],
            [
                'first_name' => 'Anika',
                'last_name' => 'Soriano',
                'date_of_birth' => '1987-11-30',
                'gender' => 'Female',
                'national_id' => 'PL98217435',
                'contact_email' => 'anikasoriano@gmail.com',
                'phone_number' => '09179884215',
                'address' => '244 Sampaguita St, Taguig',
                'job_title' => 'Operating Room Nurse',
                'department' => 'Surgical Services',
                'hire_date' => '2017-01-25',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BSN, Certified OR Nurse',
                'work_experience' => '8 years assisting in complex surgeries and managing surgical prep/post-op.',
                'allocation' => 'General Surgery',
            ],
            [
                'first_name' => 'Cyrus',
                'last_name' => 'Manalo',
                'date_of_birth' => '1992-06-17',
                'gender' => 'Male',
                'national_id' => 'JY76384219',
                'contact_email' => 'cyrusmanalo@gmail.com',
                'phone_number' => '09175530987',
                'address' => '12 Mabini Ave, Iloilo City',
                'job_title' => 'Medical Technologist',
                'department' => 'Laboratory',
                'hire_date' => '2019-08-10',
                'employment_type' => 'Full-time',
                'status' => 'On Leave',
                'qualifications' => 'BS MedTech, PRC Licensed',
                'work_experience' => '6 years running diagnostics and leading lab protocol standardization.',
                'allocation' => 'Isolation Ward',
            ],
            [
                'first_name' => 'Leona',
                'last_name' => 'Del Rosario',
                'date_of_birth' => '1983-09-04',
                'gender' => 'Female',
                'national_id' => 'KM84731952',
                'contact_email' => 'leonadelrosario@gmail.com',
                'phone_number' => '09172341234',
                'address' => '75 Quirino Highway, Quezon City',
                'job_title' => 'Head Radiologic Technologist',
                'department' => 'Radiology',
                'hire_date' => '2010-03-18',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BS RadTech, Masters in Diagnostic Imaging',
                'work_experience' => '15 years managing imaging teams and operating MRI/CT units.',
                'allocation' => 'Oncology Ward',
            ],
            [
                'first_name' => 'Robert Joshua',
                'last_name' => 'Cosep',
                'date_of_birth' => '1995-07-12',
                'gender' => 'Male',
                'national_id' => 'RJ19950712',
                'contact_email' => 'robert.cosep@gmail.com',
                'phone_number' => '09171234567',
                'address' => 'San Jose, Batangas',
                'job_title' => 'IT Support Specialist',
                'department' => 'Information Technology',
                'hire_date' => '2023-02-01',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BS Information Technology',
                'work_experience' => '2 years managing hospital systems and EHR maintenance.',
                'allocation' => 'Out-Patient Clinic',
            ],
            [
                'first_name' => 'Jhon Adrian',
                'last_name' => 'Valdehueza',
                'date_of_birth' => '1996-04-20',
                'gender' => 'Male',
                'national_id' => 'JV19960420',
                'contact_email' => 'jhon.valdehueza@gmail.com',
                'phone_number' => '09179880023',
                'address' => 'Cagayan de Oro City',
                'job_title' => 'Staff Nurse',
                'department' => 'General Ward',
                'hire_date' => '2022-06-15',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BS Nursing, PRC Licensed',
                'work_experience' => '3 years bedside care, patient monitoring, IV therapy.',
                'allocation' => 'Orthopedic Ward',
            ],
            [
                'first_name' => 'Hero',
                'last_name' => 'Cayetano',
                'date_of_birth' => '1990-01-03',
                'gender' => 'Male',
                'national_id' => 'HC19900103',
                'contact_email' => 'hero.cayetano@gmail.com',
                'phone_number' => '09171239876',
                'address' => 'Makati City',
                'job_title' => 'Pharmacist',
                'department' => 'Pharmacy',
                'hire_date' => '2021-03-10',
                'employment_type' => 'Part-time',
                'status' => 'Active',
                'qualifications' => 'BS Pharmacy, PRC Licensed',
                'work_experience' => '4 years hospital pharmacy and medication inventory control.',
                'allocation' => 'Recovery Ward',
            ],
            [
                'first_name' => 'Vinz',
                'last_name' => 'Dela Cruz',
                'date_of_birth' => '1991-09-22',
                'gender' => 'Male',
                'national_id' => 'VC19910922',
                'contact_email' => 'vinz.delacruz@gmail.com',
                'phone_number' => '09172341211',
                'address' => 'Bacoor, Cavite',
                'job_title' => 'Respiratory Therapist',
                'department' => 'ICU',
                'hire_date' => '2020-10-05',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BS Respiratory Therapy',
                'work_experience' => '5 years ICU ventilator management and patient assessment.',
                'allocation' => 'Emergency Observation',
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Estorba',
                'date_of_birth' => '1993-12-11',
                'gender' => 'Male',
                'national_id' => 'PE19931211',
                'contact_email' => 'paul.estorba@gmail.com',
                'phone_number' => '09179881145',
                'address' => 'Talisay, Cebu',
                'job_title' => 'Billing Clerk',
                'department' => 'Finance',
                'hire_date' => '2023-08-01',
                'employment_type' => 'Full-time',
                'status' => 'Active',
                'qualifications' => 'BS Accountancy',
                'work_experience' => '2 years handling billing statements and patient accounts.',
                'allocation' => 'Geriatric Ward',
            ],
        ];

        foreach ($staffMembers as $staff) {
            HospitalStaff::create($staff);
        }
    }
}
